Add a "my_services" command
sonac/burgerbot pull request #22
Opened 2022-08-16 13:52 UTC by harrybiddle

I love BurgerBot!

It would be really useful to be able to list which services you are subscribed to. I've added a command "my_services" that does this. **This is untested**! I don't know how one goes about testing a telegram bot command...

I've also snuck in another change in this PR. When I used the bot I was initially dismayed that the service I was interested in wasn't listed by the "services" command. Eventually I realised that you can add pretty much any service! This wasn't clear to me initially. So, I have altered the help text to make it clearer that the list is non-exhaustive.

2022-08-16 15:18 UTC, sonac reviewed
thanks! was thinking about adding smth like this myself, i'll test it on my dev server, cause I have some doubts about formatting of the message (how it will look like in the telegram itself)

2022-08-16 15:18 UTC, sonac commented on burgerbot.py
> +    update.message.reply_text("Example available services:\n" + services_text)
```suggestion
    update.message.reply_text("Example of available services:\n" + services_text)
```

2022-08-18 09:56 UTC, harrybiddle commented on burgerbot.py
> +    update.message.reply_text("Example of available services:\n" + services_text)
```suggestion
    update.message.reply_text("Available services:\n" + services_text)
```

2022-08-18 09:56 UTC, harrybiddle commented on burgerbot.py
> +/services - non-exhaustive list of available services
```suggestion
/services - list of available services
```

2022-08-21 09:53 UTC, sonac requested changes
All seems good, you're just missing the handler assignment in bot init (like https://github.com/sonac/burgerbot/blob/master/burgerbot.py#L71)

2022-08-22 13:57 UTC, harrybiddle commented
Aha, thanks. I've added that

2022-08-25 13:03 UTC, merged