Added service 'Residence permit for a foreign child born in Germany'
sonac/burgerbot pull request #42
Opened 2023-02-15 22:31 UTC by ajammil

2023-02-19 12:55 UTC, sonac requested changes
Services are numerically sorted, for easier search\duplicates avoidance, could you please move this one up a bit to correct place?

2023-02-20 10:30 UTC, ajammil commented
Reordered the service, and resolved merge confilcts.

2023-02-25 07:09 UTC, sonac approved these changes

2023-02-25 07:09 UTC, sonac commented
Thanks!

2023-02-25 07:09 UTC, merged